version: '3.8'

services:
  redis-db:
    image: 'redis:alpine'
#    ports:
#      - 6379:6379
    command: redis-server
    volumes:
      - redis-data:/data

  db:
    image: postgres:14
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - db-data:/var/lib/postgresql/data/

  blockscout:
    image: blockscout/blockscout:master
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    environment:
      - DATABASE_URL=postgresql://postgres:@db:5432/blockscout
      - ETHEREUM_JSONRPC_HTTP_URL=https://rpc.nice.hydration.cloud
      - SUBNETWORK=HydraDX
      - COIN=WETH
      - COIN_NAME=WETH
      - CHAIN_ID=2034
#      - LOGO=/images/acala_logo.svg
#      - FOOTER_LOGO=/images/acala_logo.svg
      - JSON_RPC=https://rpc.nice.hydration.cloud
      - SECRET_KEY_BASE=b7ICxPjuotgM3Na3Dkw2DE+i46KZlG5HS9cBwywYX8XuCS5dGLkiQYWNN6Plgf88
      - SUPPORTED_CHAINS=[]
      - INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
      - INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
      - ACCOUNT_POOL_SIZE=20
      - ACCOUNT_REDIS_URL=redis://redis-db:6379
      - INDEXER_TOKEN_BALANCES_BATCH_SIZE=10
      - INDEXER_COIN_BALANCES_BATCH_SIZE=10
      - INDEXER_RECEIPTS_BATCH_SIZE=10
      - BLOCKSCOUT_VERSION=v5.2.2-beta
      - RELEASE_LINK=https://github.com/blockscout/blockscout/releases/tag/v5.2.2-beta
    ports:
      - 4000:4000
    volumes:
      - logs/:/app/logs/

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:latest

  visualizer:
    image: ghcr.io/blockscout/visualizer:latest

  sig-provider:
    image: ghcr.io/blockscout/sig-provider:latest

volumes:
  redis-data:
    driver: local
  logs:
    driver: local
  db-data:
    driver: local
